server:
  port: 8085
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyaa-Sharmaa/Microservices-tut-Config
          clone-on-start: true
          default-label: main