spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Microservices
  application:
    name: RATINGSERVICE

  config:
    import: optional:configserver:http://localhost:8085	  
server:
  port: 8083	    	  